---
- name: 'Cria arquivo wordpress.conf'
  copy:
          src: '/vagrant/files/wordpress.conf'
          dest: '/etc/apache2/sites-available/wordpress.conf'
          remote_src: yes
  become: yes
- name: 'Enable Wordpress write'
  shell: |
          a2ensite wordpress
          a2enmod rewrite
  notify:
          - restart apache
  become: yes
- name: 'Create wp-config.php'
  copy:
          src: '/usr/share/wordpress/wp-config-sample.php'
          dest: '/usr/share/wordpress/wp-config.php'
          remote_src: yes
  become: yes
- name: 'config wordpress wp-config.php'
  replace:
          path: '/usr/share/wordpress/wp-config.php'
          regexp: "{{ item.regex }}"
          replace: "{{ item.value }}"
          backup: yes
  with_items:
          - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
          - { regex: 'username_here', value: "{{ wp_user_name }}" }
          - { regex: 'password_here', value: '12345' }
          - { regex: 'localhost', value: "{{ database_ip }}" }
  become: yes
- name: 'Configura Apache usando template'
  template:
          src: 'templates/000-default.conf.j2'
          dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
          - restart apache
