---
- name: 'Instala os MySQL Server'
  apt:
          update_cache: yes
          name:
                  - mysql-server
                  - python3-mysqldb
  become: yes
- name: 'Create wordpress database'
  mysql_db:
          name: "{{ wp_db_name }}"
          state: present
  become: yes
- name: 'Create mysql user'
  mysql_user:
          login_user: root
          name: "{{ wp_user_name }}"
          password: 12345
          priv: "{{ wp_db_name }}.*:ALL"
          state: present
          host: "{{ item }}"
  with_items:
          - "{{ wp_host_ip }}"
  become: yes
- name: 'Create backup of mysql config file'
  copy:
          src: '/etc/mysql/mysql.conf.d/mysqld.cnf'
          dest: '/etc/mysql/mysql.conf.d/backup_mysqld.cnf'
          remote_src: yes
  become: yes
- name: 'Allow mysql to be accessed from wordpress'
  replace:
          path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
          regexp: "(bind-address.*=) [0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
          replace: "bind-address              = 0.0.0.0"
          backup: yes
  notify:
          - restart mysql
  become: yes
